language: swift

osx_image: 
- xcode10.3
- xcode11.1

env:
- DESTINATION='platform=macOS' SWIFT_VERSION=5.0
- DESTINATION='platform=iOS Simulator,name=iPhone 8' SWIFT_VERSION=5.0
- DESTINATION='platform=tvOS Simulator,name=Apple TV' SWIFT_VERSION=5.0
- DESTINATION='platform=macOS' SWIFT_VERSION=4.2
- DESTINATION='platform=iOS Simulator,name=iPhone 8' SWIFT_VERSION=4.2
- DESTINATION='platform=tvOS Simulator,name=Apple TV' SWIFT_VERSION=4.2
- DESTINATION='platform=macOS' SWIFT_VERSION=4.0
- DESTINATION='platform=iOS Simulator,name=iPhone 8' SWIFT_VERSION=4.0
- DESTINATION='platform=tvOS Simulator,name=Apple TV' SWIFT_VERSION=4.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec fastlane test_ci
